export const BOSS_PERSONAS = [
  {
    id: "supportive",
    name: "サポート型 佐藤部長",
    description: "部下を励まし、建設的なフィードバックを提供する理解のある上司",
    difficulty: "初級" as const,
    traits: ["励ます", "忍耐強い", "理解がある", "建設的", "共感的"],
    scenario_types: ["performance", "feedback", "goal-setting", "team-building"],
    communicationStyle: "supportive",
  },
  {
    id: "demanding",
    name: "要求厳格型 田中執行役員",
    description: "結果重視で高いパフォーマンスと迅速な成果を求める上司",
    difficulty: "中級" as const,
    traits: ["結果重視", "厳しい", "スピード重視", "分析的", "直接的"],
    scenario_types: ["performance", "deadline-pressure", "strategic-planning"],
    communicationStyle: "direct",
  },
  {
    id: "micromanager",
    name: "細かい管理型 鈴木課長",
    description: "細部にこだわり、業務のあらゆる面をコントロールしたがる上司",
    difficulty: "中級" as const,
    traits: ["細かい", "管理的", "せっかち", "完璧主義", "監視的"],
    scenario_types: ["project-management", "quality-control", "process-improvement"],
    communicationStyle: "controlling",
  },
  {
    id: "passive-aggressive",
    name: "皮肉嫌味型 高橋マネージャー",
    description: "不満を間接的に表現し、遠回しな批判をする上司",
    difficulty: "上級" as const,
    traits: ["皮肉な", "遠回し", "予測不能", "微妙", "気分屋"],
    scenario_types: ["conflict-resolution", "feedback", "team-dynamics"],
    communicationStyle: "indirect",
  },
  {
    id: "volatile",
    name: "感情変動型 山田常務",
    description: "気分の浮き沈みが激しく、感情的な爆発をする予測不能な上司",
    difficulty: "上級" as const,
    traits: ["予測不能", "感情的", "変動的", "威圧的", "反応的"],
    scenario_types: ["crisis-management", "conflict-resolution", "pressure-situations"],
    communicationStyle: "aggressive",
  },
  {
    id: "analytical",
    name: "データ重視型 中村取締役",
    description: "データと分析に基づいて決定を下す論理的思考の上司",
    difficulty: "中級" as const,
    traits: ["論理的", "データ重視", "体系的", "質問好き", "徹底的"],
    scenario_types: ["strategic-planning", "performance", "project-management"],
    communicationStyle: "analytical",
  },
] as const;

export const SCENARIOS = [
  {
    id: "performance-review",
    title: "人事評価面談",
    description: "四半期の人事評価について建設的なフィードバックを交わす面談",
    category: "performance",
    difficulty: 5,
    estimated_duration: 15,
  },
  {
    id: "deadline-pressure",
    title: "急な締切変更への対応",
    description: "突然の締切変更とリソース制約への対処",
    category: "deadline-pressure",
    difficulty: 7,
    estimated_duration: 20,
  },
  {
    id: "team-conflict",
    title: "チーム内紛争の解決",
    description: "チームメンバー間の意見対立を仲裁する",
    category: "conflict-resolution",
    difficulty: 8,
    estimated_duration: 25,
  },
  {
    id: "budget-discussion",
    title: "予算計画会議",
    description: "予算配分とリソース計画について議論する",
    category: "strategic-planning",
    difficulty: 6,
    estimated_duration: 20,
  },
  {
    id: "goal-setting",
    title: "四半期目標設定",
    description: "四半期の明確な目標とKPIを設定する",
    category: "goal-setting",
    difficulty: 4,
    estimated_duration: 15,
  },
  {
    id: "crisis-management",
    title: "危機対応会議",
    description: "即座の対応が必要な緊急事態への対処",
    category: "crisis-management",
    difficulty: 9,
    estimated_duration: 30,
  },
  {
    id: "feedback-session",
    title: "建設的批判への対応",
    description: "建設的な批判に対してプロフェッショナルに対応する",
    category: "feedback",
    difficulty: 6,
    estimated_duration: 15,
  },
  {
    id: "project-update",
    title: "プロジェクト進捗報告",
    description: "プロジェクトの進捗を発表し、懸念事項に対処する",
    category: "project-management",
    difficulty: 5,
    estimated_duration: 20,
  },
] as const;

export const STRESS_LEVELS = [
  { value: 1, label: "とても低い", color: "green", description: "穏やかでリラックスした環境" },
  { value: 2, label: "低い", color: "green", description: "プレッシャーはほとんどない状況" },
  { value: 3, label: "やや低い", color: "yellow", description: "わずかな緊張が存在" },
  { value: 4, label: "普通", color: "yellow", description: "目立ったプレッシャー" },
  { value: 5, label: "普通", color: "yellow", description: "中程度のストレスレベル" },
  { value: 6, label: "やや高い", color: "orange", description: "プレッシャーが増加" },
  { value: 7, label: "高い", color: "orange", description: "高ストレス状況" },
  { value: 8, label: "高い", color: "red", description: "非常に高いプレッシャー" },
  { value: 9, label: "危険", color: "red", description: "激しいストレス環境" },
  { value: 10, label: "極限", color: "red", description: "最大プレッシャー状況" },
] as const;

export const QUICK_RESPONSES = [
  "承知いたしました。すぐに取り掛からせていただきます。",
  "期待していることについて、もう少し詳しく教えていただけますか？",
  "フィードバックをいただき、ありがとうございます。改善に努めます。",
  "正しく理解したいので、確認させてください。",
  "〇時までに進捗をご報告いたします。",
  "最優先事項は何でしょうか？",
  "おっしゃる通りです。どのように進めればよろしいでしょうか？",
  "ご指摘いただき、ありがとうございます。",
] as const;
